#! /bin/sh
# (c) Copyright 2019-2020, James Stevens ... see LICENSE for details
# Alternative license arrangements possible, contact me for more information

opts="daemon off;"
conf="nginx_ssl.conf"

{
echo "
worker_processes  3;

events {
    worker_connections  1024;
}

user daemon;

http {
    access_log      off;
    error_log       stderr error;
    include         mime.types;
    default_type    application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    upstream epp_servers {
"
sessions=5
if test "${DOH_SESSIONS}"; then sessions="${DOH_SESSIONS}"; fi
x=0
while test ${x} -lt ${sessions}
	do
		x=$(expr ${x} + 1)
		echo "		server unix:/ram/dnsflsk_${x}.sock;"
	done
echo "
        }

    server {
        listen 800 ssl;
        server_name localhost;

        ssl_certificate      certkey.pem;
        ssl_certificate_key  certkey.pem;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;


        location / {
            proxy_pass http://epp_servers;
        }
    }
}"

} > /ram/${conf}

sleep 1
exec /usr/sbin/nginx -c /etc/nginx/${conf} -g "${opts}"
